[package]
name = "git-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.45", features = ["derive"] }
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
serde_json = "1.0.142"
